export const withdrawals = [
  {
    withdrawalId: "W00001",
    createdUser: "john.doe@gmail.com",
    amount: 500,
    status: "Pending",
    method: "Crypto",
    withdrawalDate: "2024-05-01",
    notes: "Test note 1",
  },
  {
    withdrawalId: "W00002",
    createdUser: "alice.smith@outlook.com",
    amount: 300,
    status: "Approved",
    method: "USDT",
    withdrawalDate: "2024-05-02",
    notes: "Test note 2",
  },
  {
    withdrawalId: "W00003",
    createdUser: "bob.johnson@yahoo.com",
    amount: 700,
    status: "Rejected",
    method: "Crypto",
    withdrawalDate: "2024-05-03",
    notes: "Test note 3",
  },
  {
    withdrawalId: "W00004",
    createdUser: "ella.davis@otherbusiness.com",
    amount: 400,
    status: "Pending",
    method: "USDT",
    withdrawalDate: "2024-05-04",
    notes: "Test note 4",
  },
  {
    withdrawalId: "W00005",
    createdUser: "david.wilson@gmail.com",
    amount: 600,
    status: "Approved",
    method: "Crypto",
    withdrawalDate: "2024-05-05",
    notes: "Test note 5",
  },
  {
    withdrawalId: "W00006",
    createdUser: "emma.martinez@outlook.com",
    amount: 200,
    status: "Pending",
    method: "Crypto",
    withdrawalDate: "2024-05-06",
    notes: "Test note 6",
  },
  {
    withdrawalId: "W00007",
    createdUser: "charlie.brown@yahoo.com",
    amount: 800,
    status: "Approved",
    method: "USDT",
    withdrawalDate: "2024-05-07",
    notes: "Test note 7",
  },
  {
    withdrawalId: "W00008",
    createdUser: "sarah.jones@otherbusiness.com",
    amount: 350,
    status: "Rejected",
    method: "Crypto",
    withdrawalDate: "2024-05-08",
    notes: "Test note 8",
  },
  {
    withdrawalId: "W00009",
    createdUser: "michael.smith@gmail.com",
    amount: 450,
    status: "Pending",
    method: "USDT",
    withdrawalDate: "2024-05-09",
    notes: "Test note 9",
  },
  {
    withdrawalId: "W00010",
    createdUser: "linda.johnson@outlook.com",
    amount: 550,
    status: "Approved",
    method: "Crypto",
    withdrawalDate: "2024-05-10",
    notes: "Test note 10",
  },
  {
    withdrawalId: "W00011",
    createdUser: "peter.wang@yahoo.com",
    amount: 650,
    status: "Rejected",
    method: "USDT",
    withdrawalDate: "2024-05-11",
    notes: "Test note 11",
  },
  {
    withdrawalId: "W00012",
    createdUser: "emily.jackson@gmail.com",
    amount: 750,
    status: "Pending",
    method: "Crypto",
    withdrawalDate: "2024-05-12",
    notes: "Test note 12",
  },
  {
    withdrawalId: "W00013",
    createdUser: "adam.miller@outlook.com",
    amount: 850,
    status: "Approved",
    method: "USDT",
    withdrawalDate: "2024-05-13",
    notes: "Test note 13",
  },
  {
    withdrawalId: "W00014",
    createdUser: "susan.davis@yahoo.com",
    amount: 950,
    status: "Rejected",
    method: "Crypto",
    withdrawalDate: "2024-05-14",
    notes: "Test note 14",
  },
  {
    withdrawalId: "W00015",
    createdUser: "kevin.white@otherbusiness.com",
    amount: 550,
    status: "Pending",
    method: "USDT",
    withdrawalDate: "2024-05-15",
    notes: "Test note 15",
  },
  {
    withdrawalId: "W00016",
    createdUser: "sophia.brown@gmail.com",
    amount: 650,
    status: "Approved",
    method: "Crypto",
    withdrawalDate: "2024-05-16",
    notes: "Test note 16",
  },
  {
    withdrawalId: "W00017",
    createdUser: "jacob.jones@outlook.com",
    amount: 750,
    status: "Rejected",
    method: "USDT",
    withdrawalDate: "2024-05-17",
    notes: "Test note 17",
  },
  {
    withdrawalId: "W00018",
    createdUser: "olivia.taylor@yahoo.com",
    amount: 850,
    status: "Pending",
    method: "Crypto",
    withdrawalDate: "2024-05-18",
    notes: "Test note 18",
  },
  {
    withdrawalId: "W00019",
    createdUser: "william.clark@otherbusiness.com",
    amount: 950,
    status: "Approved",
    method: "USDT",
    withdrawalDate: "2024-05-19",
    notes: "Test note 19",
  },
  {
    withdrawalId: "W00020",
    createdUser: "lucy.hall@gmail.com",
    amount: 400,
    status: "Rejected",
    method: "Crypto",
    withdrawalDate: "2024-05-20",
    notes: "Test note 20",
  },
  {
    withdrawalId: "W00021",
    createdUser: "mason.king@outlook.com",
    amount: 1100,
    status: "Pending",
    method: "USDT",
    withdrawalDate: "2024-05-21",
    notes: "Test note 21",
  },
  {
    withdrawalId: "W00022",
    createdUser: "ava.anderson@yahoo.com",
    amount: 600,
    status: "Approved",
    method: "Crypto",
    withdrawalDate: "2024-05-22",
    notes: "Test note 22",
  },
  {
    withdrawalId: "W00023",
    createdUser: "noah.morris@gmail.com",
    amount: 850,
    status: "Rejected",
    method: "USDT",
    withdrawalDate: "2024-05-23",
    notes: "Test note 23",
  },
  {
    withdrawalId: "W00024",
    createdUser: "mia.ross@outlook.com",
    amount: 300,
    status: "Pending",
    method: "Crypto",
    withdrawalDate: "2024-05-24",
    notes: "Test note 24",
  },
  {
    withdrawalId: "W00025",
    createdUser: "jack.lee@otherbusiness.com",
    amount: 1250,
    status: "Approved",
    method: "USDT",
    withdrawalDate: "2024-05-25",
    notes: "Test note 25",
  },
  {
    withdrawalId: "W00026",
    createdUser: "hannah.wright@gmail.com",
    amount: 700,
    status: "Rejected",
    method: "Crypto",
    withdrawalDate: "2024-05-26",
    notes: "Test note 26",
  },
  {
    withdrawalId: "W00027",
    createdUser: "ethan.harris@outlook.com",
    amount: 950,
    status: "Pending",
    method: "USDT",
    withdrawalDate: "2024-05-27",
    notes: "Test note 27",
  },
  {
    withdrawalId: "W00028",
    createdUser: "amelia.cooper@yahoo.com",
    amount: 800,
    status: "Approved",
    method: "Crypto",
    withdrawalDate: "2024-05-28",
    notes: "Test note 28",
  },
  {
    withdrawalId: "W00029",
    createdUser: "jackson.ross@otherbusiness.com",
    amount: 900,
    status: "Rejected",
    method: "USDT",
    withdrawalDate: "2024-05-29",
    notes: "Test note 29",
  },
  {
    withdrawalId: "W00030",
    createdUser: "emma.brown@gmail.com",
    amount: 400,
    status: "Pending",
    method: "Crypto",
    withdrawalDate: "2024-05-30",
    notes: "Test note 30",
  },
];
