export const deposits = [
  {
    depositId: "D123456",
    createdUser: "john.doe@gmail.com",
    amount: 1000,
    status: "Completed",
    method: "Crypto",
    depositDate: "2024-05-01",
    notes: "Test note 1",
  },
  {
    depositId: "D234567",
    createdUser: "alice.smith@outlook.com",
    amount: 500,
    status: "Pending",
    method: "USDT",
    depositDate: "2024-05-02",
    notes: "Test note 2",
  },
  {
    depositId: "D345678",
    createdUser: "bob.johnson@yahoo.com",
    amount: 750,
    status: "Completed",
    method: "Crypto",
    depositDate: "2024-05-03",
    notes: "Test note 3",
  },
  {
    depositId: "D456789",
    createdUser: "ella.davis@otherbusiness.com",
    amount: 300,
    status: "Failed",
    method: "USDT",
    depositDate: "2024-05-04",
    notes: "Test note 4",
  },
  {
    depositId: "D567890",
    createdUser: "david.wilson@gmail.com",
    amount: 1200,
    status: "Completed",
    method: "Crypto",
    depositDate: "2024-05-05",
    notes: "Test note 5",
  },
  {
    depositId: "D678901",
    createdUser: "emma.martinez@outlook.com",
    amount: 800,
    status: "Pending",
    method: "USDT",
    depositDate: "2024-05-06",
    notes: "Test note 6",
  },
  {
    depositId: "D789012",
    createdUser: "charlie.brown@yahoo.com",
    amount: 950,
    status: "Completed",
    method: "Crypto",
    depositDate: "2024-05-07",
    notes: "Test note 7",
  },
  {
    depositId: "D890123",
    createdUser: "sarah.jones@otherbusiness.com",
    amount: 700,
    status: "Pending",
    method: "USDT",
    depositDate: "2024-05-08",
    notes: "Test note 8",
  },
  {
    depositId: "D901234",
    createdUser: "michael.smith@gmail.com",
    amount: 850,
    status: "Completed",
    method: "Crypto",
    depositDate: "2024-05-09",
    notes: "Test note 9",
  },
  {
    depositId: "D012345",
    createdUser: "linda.johnson@outlook.com",
    amount: 400,
    status: "Pending",
    method: "USDT",
    depositDate: "2024-05-10",
    notes: "Test note 10",
  },
  {
    depositId: "D123450",
    createdUser: "peter.wang@yahoo.com",
    amount: 1100,
    status: "Completed",
    method: "Crypto",
    depositDate: "2024-05-11",
    notes: "Test note 11",
  },
  {
    depositId: "D234567",
    createdUser: "emily.jackson@gmail.com",
    amount: 600,
    status: "Pending",
    method: "USDT",
    depositDate: "2024-05-12",
    notes: "Test note 12",
  },
  {
    depositId: "D345678",
    createdUser: "adam.miller@outlook.com",
    amount: 850,
    status: "Completed",
    method: "Crypto",
    depositDate: "2024-05-13",
    notes: "Test note 13",
  },
  {
    depositId: "D456789",
    createdUser: "susan.davis@yahoo.com",
    amount: 300,
    status: "Failed",
    method: "USDT",
    depositDate: "2024-05-14",
    notes: "Test note 14",
  },
  {
    depositId: "D567890",
    createdUser: "kevin.white@otherbusiness.com",
    amount: 1250,
    status: "Completed",
    method: "Crypto",
    depositDate: "2024-05-15",
    notes: "Test note 15",
  },
  {
    depositId: "D678901",
    createdUser: "sophia.brown@gmail.com",
    amount: 700,
    status: "Pending",
    method: "USDT",
    depositDate: "2024-05-16",
    notes: "Test note 16",
  },
  {
    depositId: "D789012",
    createdUser: "jacob.jones@outlook.com",
    amount: 950,
    status: "Completed",
    method: "Crypto",
    depositDate: "2024-05-17",
    notes: "Test note 17",
  },
  {
    depositId: "D890123",
    createdUser: "olivia.taylor@yahoo.com",
    amount: 800,
    status: "Pending",
    method: "USDT",
    depositDate: "2024-05-18",
    notes: "Test note 18",
  },
  {
    depositId: "D901234",
    createdUser: "william.clark@otherbusiness.com",
    amount: 900,
    status: "Completed",
    method: "Crypto",
    depositDate: "2024-05-19",
    notes: "Test note 19",
  },
  {
    depositId: "D012345",
    createdUser: "lucy.hall@gmail.com",
    amount: 400,
    status: "Pending",
    method: "USDT",
    depositDate: "2024-05-20",
    notes: "Test note 20",
  },
  {
    depositId: "D123450",
    createdUser: "mason.king@outlook.com",
    amount: 1100,
    status: "Completed",
    method: "Crypto",
    depositDate: "2024-05-21",
    notes: "Test note 21",
  },
  {
    depositId: "D234567",
    createdUser: "ava.anderson@yahoo.com",
    amount: 600,
    status: "Pending",
    method: "USDT",
    depositDate: "2024-05-22",
    notes: "Test note 22",
  },
  {
    depositId: "D345678",
    createdUser: "noah.morris@gmail.com",
    amount: 850,
    status: "Completed",
    method: "Crypto",
    depositDate: "2024-05-23",
    notes: "Test note 23",
  },
  {
    depositId: "D456789",
    createdUser: "mia.ross@outlook.com",
    amount: 300,
    status: "Failed",
    method: "USDT",
    depositDate: "2024-05-24",
    notes: "Test note 24",
  },
  {
    depositId: "D567890",
    createdUser: "jack.lee@otherbusiness.com",
    amount: 1250,
    status: "Completed",
    method: "Crypto",
    depositDate: "2024-05-25",
    notes: "Test note 25",
  },
  {
    depositId: "D678901",
    createdUser: "hannah.wright@gmail.com",
    amount: 700,
    status: "Pending",
    method: "USDT",
    depositDate: "2024-05-26",
    notes: "Test note 26",
  },
  {
    depositId: "D789012",
    createdUser: "ethan.harris@outlook.com",
    amount: 950,
    status: "Completed",
    method: "Crypto",
    depositDate: "2024-05-27",
    notes: "Test note 27",
  },
  {
    depositId: "D890123",
    createdUser: "amelia.cooper@yahoo.com",
    amount: 800,
    status: "Pending",
    method: "USDT",
    depositDate: "2024-05-28",
    notes: "Test note 28",
  },
  {
    depositId: "D901234",
    createdUser: "jackson.ross@otherbusiness.com",
    amount: 900,
    status: "Completed",
    method: "Crypto",
    depositDate: "2024-05-29",
    notes: "Test note 29",
  },
  {
    depositId: "D012345",
    createdUser: "emma.brown@gmail.com",
    amount: 400,
    status: "Pending",
    method: "USDT",
    depositDate: "2024-05-30",
    notes: "Test note 30",
  },
  {
    depositId: "D123450",
    createdUser: "michael.long@outlook.com",
    amount: 1100,
    status: "Completed",
    method: "Crypto",
    depositDate: "2024-05-31",
    notes: "Test note 31",
  },
  {
    depositId: "D234567",
    createdUser: "olivia.hall@yahoo.com",
    amount: 600,
    status: "Pending",
    method: "USDT",
    depositDate: "2024-06-01",
    notes: "Test note 32",
  },
  {
    depositId: "D345678",
    createdUser: "william.cox@gmail.com",
    amount: 850,
    status: "Completed",
    method: "Crypto",
    depositDate: "2024-06-02",
    notes: "Test note 33",
  },
  {
    depositId: "D456789",
    createdUser: "isabella.white@outlook.com",
    amount: 300,
    status: "Failed",
    method: "USDT",
    depositDate: "2024-06-03",
    notes: "Test note 34",
  },
  {
    depositId: "D567890",
    createdUser: "ethan.ross@otherbusiness.com",
    amount: 1250,
    status: "Completed",
    method: "Crypto",
    depositDate: "2024-06-04",
    notes: "Test note 35",
  },
];
